import type { Lesson, Question } from "./curriculum";
const q = (prompt: string, options: Question["options"], correct: number, explanations: Question["explanations"]): Question => ({prompt,options,correct,explanations});
export const foundationsTraffic: Lesson[] = [
{
 id:"latency-throughput",deck:0,title:"Fast vs. a lot of fast",hook:"Two numbers. Two very different stories.",
 idea:"Latency measures how long one operation takes. Throughput measures how many operations finish in a period of time. A service might answer one request in 100 milliseconds while completing 2,000 requests per second because many requests run concurrently. These numbers describe different properties. Improving one does not automatically improve the other. Also say what you measured: server processing time is only part of the delay a person experiences.",
 analogy:"At a café, latency is your wait for a coffee. Throughput is the number of coffees served each minute. Adding another barista can serve more customers without making the espresso machine brew your individual coffee any faster.",
 example:"A photo service batches uploads to process more pictures per second. That improves throughput, but someone might wait longer while the batch fills. Track a high percentile such as p95: 95 percent of measured requests finish at or below that duration. An average can hide very slow experiences.",
 tradeoff:"Pushing traffic beyond capacity creates queues and makes latency worse. Test at realistic loads, watch errors alongside speed, and choose targets around what users actually need rather than chasing the biggest benchmark number.",
 takeaway:"Latency is one wait. Throughput is work per second.",diagram:["Requests","Parallel work","Completions"],caption:"Time one trip for latency; count finished trips per second for throughput.",recall:"How can throughput increase while one person’s wait stays the same?",
 questions:[q("Which measurement describes throughput?",["200 milliseconds per response","500 completed requests per second","The slowest response today"],1,["That is latency: the duration of a response.","Right. Throughput counts completed work per unit of time.","That is a latency observation, not a work rate."]),q("The average looks good, but some users wait ages. What should you inspect?",["Only the average again","Only the server count","Tail latency such as p95 and p99"],2,["An average can conceal the slow tail.","Server count does not describe the actual user experience.","Exactly. High percentiles reveal slow experiences hidden by the average."])]
},
{
 id:"availability",deck:0,title:"Open when it matters",hook:"A running server isn’t always a working app.",
 idea:"Availability describes whether people can successfully use a service when they need it. Define success first: perhaps a checkout must finish correctly within two seconds. A server that answers every request with an error is reachable but not useful. Teams often measure the fraction of eligible requests that succeed over a stated window. Others measure uptime. Be explicit, because those measurements can tell different stories during partial failures.",
 analogy:"A café with its lights on but no working coffee machine is technically open. From a coffee drinker’s perspective, it is unavailable. A second machine helps only if the same broken power supply does not disable both.",
 example:"An online store can run application instances in separate failure zones. Health checks stop sending traffic to a broken instance. If recommendations fail, checkout can still work with a simpler page. This is graceful degradation: protect the essential journey before the optional extras.",
 tradeoff:"Redundancy costs money and creates failover work. Shared dependencies can still bring everything down. Pick a useful target, test recovery, and measure real user success. A 99.9 percent target is a budget for failures over a chosen window, not a promise that every user sees identical reliability.",
 takeaway:"Available means the user’s job still gets done.",diagram:["User","Healthy instance","Successful task"],caption:"Route around failed instances; check shared dependencies too.",recall:"Why can a reachable service still be unavailable to its users?",
 questions:[q("Which is the most useful checkout availability signal?",["The server’s light is on","The homepage is colorful","Checkouts succeed within the target"],2,["A running machine can still return errors.","Appearance does not measure successful purchases.","Yes. Availability should reflect the user’s successful journey."]),q("Recommendations are down. How should checkout respond?",["Continue without recommendations","Fail every purchase","Wait forever"],0,["Correct. Graceful degradation protects the essential purchase journey.","That makes an optional dependency a critical failure.","An unbounded wait is effectively a failure for the user."])]
},
{
 id:"scaling",deck:0,title:"Bigger kitchen, or more kitchens?",hook:"Meet the two directions of scale.",
 idea:"Vertical scaling gives one machine more resources, such as memory or CPU. Horizontal scaling adds more machines and distributes work among them. Both can increase capacity, but only when they address the actual bottleneck. More application servers will not fix a database query that scans every record. Start by measuring resource use and the time spent in each part of the request, then choose the smallest useful change.",
 analogy:"A busy bakery can buy a larger oven or open another kitchen. A larger oven is easy to use until you hit its limit. Multiple kitchens increase capacity, but now orders, ingredients, and recipes must be coordinated.",
 example:"A stateless web application can run behind a load balancer on several instances. Each request carries enough information to work on any instance, while durable data lives in shared storage. If login sessions exist only in one instance’s memory, sending the next request elsewhere may appear to log the user out.",
 tradeoff:"Vertical scaling has hardware limits and may require downtime. Horizontal scaling adds network and coordination complexity. Neither creates unlimited capacity or automatic reliability. Scale the constrained component, plan how state is shared, and test what happens when one instance disappears during real traffic.",
 takeaway:"Scale up for a bigger machine; scale out for more machines.",diagram:["Traffic","Load balancer","App instances"],caption:"Horizontal scaling distributes work; shared state needs its own plan.",recall:"What is the difference between scaling up and scaling out?",
 questions:[q("Adding another application instance is…",["Vertical scaling","Horizontal scaling","Database indexing"],1,["Vertical scaling adds resources to one machine.","Exactly. Horizontal scaling adds instances.","Indexing changes data access, not the application instance count."]),q("Logins vanish when requests switch servers. What needs attention?",["The button color","Uncoordinated local session copies","A session strategy across instances"],2,["This is a state problem, not a visual one.","Separate copies can diverge and preserve the problem.","Yes. Shared session storage or a suitable verifiable token can let any instance handle the request."])]
},
{
 id:"load-balancing",deck:1,title:"Share the rush",hook:"One front door. Many helping hands.",
 idea:"A load balancer distributes incoming traffic among application instances. It gives clients a stable entry point while the set of healthy servers changes underneath. Round robin takes turns; least connections favors an instance with fewer active connections. Neither knows everything about the cost of a request. Health checks help remove unhealthy targets, but a shallow check may miss a broken dependency that real requests still need.",
 analogy:"A restaurant host guides guests to different servers instead of letting everyone crowd around the first person they see. Counting tables is useful, but a table ordering ten courses needs more attention than one ordering tea.",
 example:"An image API runs on three instances. The balancer sends new requests to healthy instances while one is replaced. Existing work needs time to finish, so graceful draining stops new traffic before shutdown. Shared session state lets a later request land on a different instance without losing the user’s session.",
 tradeoff:"A balancer adds a network step and must itself be reliable. Sticky sessions can simplify local state temporarily, but uneven traffic and instance failures remain. Measure request duration, errors, and load per instance. More evenly distributed connections do not necessarily mean more evenly distributed work.",
 takeaway:"Balance the work, and keep checking who can do it.",diagram:["Requests","Balancer","Healthy apps"],caption:"The balancer selects a healthy target for each request or connection.",recall:"Why might equal connection counts still produce uneven server load?",
 questions:[q("What is a load balancer’s main job?",["Distribute incoming traffic","Store every user record","Make all requests equally expensive"],0,["Yes. It routes work among eligible targets.","Persistent records belong in a data store.","Request costs vary; balancing does not erase that difference."]),q("You are removing an instance with active requests. What helps?",["Delete it immediately","Stop new traffic and drain existing work","Send it more traffic"],1,["Immediate removal can interrupt work.","Correct. Draining gives in-flight work a chance to finish.","More traffic increases the work that might be interrupted."])]
},
{
 id:"reverse-proxies",deck:1,title:"Meet the front desk",hook:"A helpful middle layer for your servers.",
 idea:"A reverse proxy receives requests on behalf of backend servers and forwards them to the appropriate destination. Clients talk to the proxy instead of directly addressing each internal service. It can handle TLS connections, route by URL path, enforce request limits, or cache selected responses. Load balancing is one capability a reverse proxy may provide; the terms overlap, but they describe different responsibilities rather than two mutually exclusive products.",
 analogy:"At a hotel, the front desk directs your request to housekeeping or the kitchen. You do not need their private phone numbers. The desk can apply shared rules, but it must still pass along the right information.",
 example:"An application sends requests for /images to an image service and /orders to an order service behind one public hostname. The proxy terminates the client’s TLS connection. If backend traffic crosses an untrusted network, protect that connection too. Forwarded identity and address headers must be accepted only from trusted proxies.",
 tradeoff:"Centralizing shared behavior reduces duplication but creates an important failure point. Misconfigured caching or routing can affect many services at once. Keep rules understandable, set appropriate timeouts, and test real routes. A reverse proxy does not replace authorization checks inside the application.",
 takeaway:"The proxy is the front desk, not the whole hotel.",diagram:["Client","Reverse proxy","Backend service"],caption:"Route by hostname or path; the backend still owns application authorization.",recall:"What can a reverse proxy centralize, and what must the application still check?",
 questions:[q("Who does a reverse proxy represent?",["Only the user’s laptop","Backend servers","The database’s disk"],1,["A forward proxy commonly acts for clients; this one fronts servers.","Exactly. Clients reach the proxy on behalf of backend services.","A reverse proxy handles network requests, not disk ownership."]),q("A proxy terminates HTTPS. Is application authorization still needed?",["No, encryption proves permission","Only for images","Yes, each action still needs permission checks"],2,["Encryption protects transport; it does not grant permission.","Authorization depends on the action and resource, not just file type.","Correct. A secure connection does not establish permission to perform an action."])]
},
{
 id:"cdn",deck:1,title:"Closer is quicker",hook:"Give your content a neighborhood home.",
 idea:"A content delivery network, or CDN, places servers in many locations so users can retrieve suitable content from a nearby edge. On a cache hit, the edge can answer without fetching from the origin server. On a miss, it may request the content from the origin and cache the result. Shorter network trips and fewer origin requests can improve performance, particularly for frequently requested static assets such as images and scripts.",
 analogy:"A bakery supplies neighborhood kiosks instead of making every customer travel to its central kitchen. The kiosk serves what it has. When an item is missing, someone still needs to visit the kitchen before handing it over.",
 example:"A learning site publishes versioned image filenames and long cache lifetimes. A new illustration receives a new filename so old copies can remain safely cached. Personalized account pages need different rules: accidentally sharing one user’s response with others is a serious correctness problem, even if it loads quickly.",
 tradeoff:"Cached copies may become stale, and a miss still depends on the origin. Define which responses are shareable, how cache keys vary, and when entries expire or are purged. A CDN can accelerate delivery, but it does not automatically solve slow database queries or every application bottleneck.",
 takeaway:"Move reusable content closer; keep private content private.",diagram:["User","Nearby edge","Origin on miss"],caption:"A hit stops at the edge. A miss needs an origin fetch before the response returns.",recall:"What is the difference between a CDN cache hit and a miss?",
 questions:[q("When can a CDN avoid fetching from the origin?",["On a usable cache hit","On every request forever","Only after deleting its cache"],0,["Right. The edge can serve a reusable cached response.","Misses and uncacheable responses still need the origin.","Deleting the cache causes more misses."]),q("Which is a good default CDN candidate?",["A private account balance shared across users","A versioned public illustration","An unreviewed personalized response"],1,["Private account data must not leak through a shared cache.","Yes. Public versioned assets work well with long cache lifetimes.","Personalized responses need explicit privacy and cache-key rules."])]
},
{
 id:"rate-limiting",deck:1,title:"A bouncer for your API",hook:"Protect capacity without slamming the door.",
 idea:"Rate limiting controls how much work a caller can request over time. A policy might allow an account a certain number of requests each minute. Token buckets add tokens at a steady rate and spend a token per request; stored tokens allow a limited burst. A fixed window is simpler but may allow a large burst around the boundary between windows. Choose limits around the resource you need to protect.",
 analogy:"An arcade gives you new tokens gradually. You can save a few for a short burst of games, but cannot play forever at unlimited speed. The bucket’s capacity controls the burst, while the refill rate controls sustained use.",
 example:"A costly report endpoint has a per-account limit. When the budget runs out, it responds with HTTP 429 and useful retry guidance. Other accounts retain their share of capacity. An IP-only policy can unfairly group people behind the same office network, so caller identity and abuse patterns matter.",
 tradeoff:"Distributed limiters must coordinate counts or accept approximation. The limiter itself adds work and may fail. Decide whether a failure should allow or reject requests based on the endpoint’s risk. Rate limits complement authentication and capacity planning; they do not make unlimited traffic inexpensive.",
 takeaway:"A rate limit is a budget, not a permanent ban.",diagram:["Caller","Token budget","API if allowed"],caption:"A request spends a token; an empty budget produces a limited response such as 429.",recall:"How does a token bucket allow bursts while limiting sustained traffic?",
 questions:[q("What does a token bucket’s refill rate control?",["The database schema","Sustained request allowance","The size of each response"],1,["A token bucket controls traffic, not data structure.","Correct. New tokens define how quickly the long-run allowance replenishes.","Response size is a different resource dimension."]),q("An account hits its request limit. Which response helps it recover?",["Retry instantly forever","Pretend the request succeeded","Return 429 with retry guidance"],2,["Immediate repeated retries create more load.","False success loses the caller’s work or misleads them.","Yes. Clear rate-limit feedback lets the caller back off appropriately."])]
},
];
