import type { Lesson, Question } from "./curriculum";
const q = (prompt: string, options: Question["options"], correct: number, explanations: Question["explanations"]): Question => ({prompt,options,correct,explanations});
export const dataCache: Lesson[] = [
{
 id:"sql-nosql",deck:2,title:"Give your data a good home",hook:"Start with the questions you need to ask.",
 idea:"Relational databases organize data into tables and support relationships, constraints, and queries using SQL. NoSQL is an umbrella covering several models, including documents, key-value records, wide columns, and graphs. It is not one technology with one set of guarantees. Some nonrelational databases support transactions, and relational databases can scale horizontally with suitable designs. Choose by access patterns and correctness needs instead of treating either label as a universal winner.",
 analogy:"A library might use carefully linked catalog records, while a recipe box stores each recipe as a complete card. Both organize information well for different tasks. Neither becomes useful simply because its container looks more modern.",
 example:"An ordering system needs to connect customers, orders, and payments while enforcing constraints. A relational model is a sensible starting point. A content catalog that usually reads an entire document at once may fit a document database. First write down the important reads, writes, relationships, and transaction boundaries.",
 tradeoff:"Flexible documents can reduce joins but duplicate information, making updates harder to coordinate. Normalized tables reduce certain duplication but may require joins and careful indexes. Evaluate the actual database’s guarantees, operational cost, and query behavior. The best storage choice fits the workload you have, not a slogan about scale.",
 takeaway:"Choose the access pattern before choosing the database label.",diagram:["Access patterns","Data model","Database choice"],caption:"Start with reads, writes, and correctness constraints; select a model that fits them.",recall:"Why is “NoSQL scales, SQL doesn’t” a misleading shortcut?",
 questions:[q("What should guide a database choice first?",["Reads, writes, and correctness needs","The newest logo","The shortest product name"],0,["Yes. Access patterns and guarantees reveal the actual requirements.","Novelty does not establish workload fit.","Naming has no relationship to data correctness or performance."]),q("Orders need linked records and multi-record constraints. A sensible starting point?",["A file with no validation","A relational database","Assume all NoSQL databases are identical"],1,["Missing validation makes invariants harder to enforce.","Correct. Relational constraints and transactions suit this starting requirement.","NoSQL covers different models and guarantees; evaluate a specific product."])]
},
{
 id:"indexes",deck:2,title:"The shortcut in the stacks",hook:"Find the row without reading the room.",
 idea:"An index is an extra data structure that helps the database locate rows without scanning an entire table. A common B-tree index keeps values in an ordered structure useful for equality and range lookups. The database’s query planner decides whether using an index is worthwhile. If a query returns most of a table, a scan can still be cheaper. An index is a possible shortcut, not a command to the planner.",
 analogy:"A book’s index points from a subject to relevant pages. Finding every mention of caching is quicker than reading every page. But if you need the whole book, hopping through an index may waste effort instead of saving it.",
 example:"A user lookup filters by email. An index on that column can avoid checking every user. A compound index on account and creation time may suit queries for one account’s recent orders. Column order and the query’s filters matter, so inspect an execution plan and test with realistic data.",
 tradeoff:"Indexes use storage and must be maintained when data changes, making writes more expensive. Adding one to every column is rarely wise. Measure the queries that matter, verify that an index helps, and remove unused structures carefully after checking the workloads that depend on them.",
 takeaway:"An index buys faster reads with space and write work.",diagram:["Query","Index lookup","Matching rows"],caption:"An index narrows the search; the planner may still prefer a scan for broad queries.",recall:"What do you pay for an index, even when it speeds up a read?",
 questions:[q("Which cost comes with adding an index?",["All reads become slower","More storage and write maintenance","No cost at all"],1,["Useful indexes often speed up selected reads.","Right. Extra structures consume space and must track changes.","The shortcut needs storage and update work."]),q("A query returns nearly every row. Must it use an index?",["Yes, every index is always faster","Yes, otherwise the database is broken","No, a table scan may be cheaper"],2,["Reading almost everything can make an index unhelpful.","The planner can correctly choose a scan.","Exactly. A scan can be efficient when most rows are needed."])]
},
{
 id:"replication",deck:2,title:"Copies with a catch",hook:"More copies, more places to read.",
 idea:"Replication keeps copies of data on multiple database nodes. In a common primary-and-replica setup, the primary accepts writes and replicas receive the changes. Asynchronous replication acknowledges a write before every replica has applied it, so replicas can lag. Synchronous replication waits for specified acknowledgments before reporting success. The precise durability and visibility guarantees depend on what those acknowledgments mean and how the database is configured.",
 analogy:"Imagine a teacher’s master notebook and students copying updates. Fast copying keeps the notes similar, but someone reading a student’s page immediately after an announcement may still see yesterday’s answer. Waiting for everyone changes the pace of the class.",
 example:"A profile update succeeds on the primary. An immediate read from a lagging replica may show the old name. A read-your-writes strategy might route that user’s next read to the primary. Replicas can help distribute read traffic and support failover, but promotion needs coordination to avoid conflicting writers.",
 tradeoff:"Waiting for replication can increase write latency and reduce availability during failures. Not waiting can allow stale reads or lost acknowledged writes after certain failovers. Replication is also not a backup: accidental deletions can be copied everywhere. Keep separate recovery procedures and test them before depending on redundancy.",
 takeaway:"Copies improve options; they do not remove coordination.",diagram:["Write","Primary","Replica later"],caption:"Asynchronous replication can lag, so a replica read may temporarily return older data.",recall:"Why might a successful profile edit briefly appear to disappear?",
 questions:[q("What can asynchronous replication permit?",["Temporary replica lag","Guaranteed zero-latency writes everywhere","A replacement for backups"],0,["Yes. Replicas may apply changes after the primary acknowledges them.","Network and replication work still take time.","Mistakes can replicate too; recovery needs a separate backup strategy."]),q("A user must see their own just-saved edit. What helps?",["Randomly read any replica","Use a suitable read-your-writes strategy","Delete the primary"],1,["A random replica could still be behind.","Correct. Routing or consistency guarantees can preserve that user’s read-after-write behavior.","Removing the primary does not ensure a fresh read."])]
},
{
 id:"sharding",deck:2,title:"Split the bookshelf",hook:"Different records, different homes.",
 idea:"Sharding partitions a dataset across different database nodes. Unlike replication, which copies data, sharding places different subsets on different shards. A shard key determines where a record belongs. Hashing a user ID can distribute users relatively evenly, while range partitioning groups nearby values. Good distribution requires thinking about traffic as well as record counts: a few extremely busy keys can overload one shard even when storage looks balanced.",
 analogy:"A library divides books among branches. Sorting by a code makes placement predictable, but if every student wants the same popular book, its branch still gets crowded. Equal shelf sizes do not guarantee equal queues at the desk.",
 example:"A messaging service groups messages by conversation ID, making one conversation easy to retrieve from a single shard. A very large public conversation may become a hotspot. Queries across all conversations need coordination or a separate aggregation path, and adding shards may require moving existing data safely.",
 tradeoff:"Sharding increases capacity but complicates joins, transactions, rebalancing, and operations. It is not usually the first answer to a slow query. Improve indexing and measure limits first. When sharding is justified, choose a key based on access patterns, test skew, and plan how the partition map changes over time.",
 takeaway:"Replicate for copies. Shard for different pieces.",diagram:["Record key","Shard routing","Owning shard"],caption:"The partition map assigns records to shards; each shard can also have replicas.",recall:"How does sharding differ from replication, and what creates a hotspot?",
 questions:[q("What does sharding distribute?",["Only identical copies","Different subsets of the dataset","Only application CSS"],1,["Identical copies describe replication.","Exactly. Each shard owns part of the data.","Sharding concerns data placement, not page styles."]),q("One celebrity’s records dominate traffic on a shard. What happened?",["All shards must be equally busy","Replication erased the traffic","A hot key created uneven load"],2,["Equal record counts do not ensure equal request counts.","Copies do not make the requests disappear.","Right. Shard-key traffic skew can create a hotspot."])]
},
{
 id:"cache-aside",deck:3,title:"Keep the answer handy",hook:"Why fetch it twice if once will do?",
 idea:"A cache stores reusable results so a system can avoid repeating expensive work. With cache-aside, the application checks the cache first. A hit returns the cached value. On a miss, the application reads the source of truth, puts a copy in the cache, and returns the result. The application controls this sequence. The cache is an optimization around the database, not automatically the durable owner of the data.",
 analogy:"You write a frequently used phone number on a sticky note beside your desk. The note is quick to read. If it is missing, you consult the address book and make a new note. The address book remains the authoritative record.",
 example:"A catalog caches product descriptions by product ID. Many readers reuse the same description without repeating the database query. Updating a product also requires an invalidation or refresh strategy. A miss after eviction is normal, so the database path must work even when no cached entry exists.",
 tradeoff:"Caching adds stale-data risks and another moving part. A low hit rate may add a network hop without saving much work. Measure hit rate, latency, and database load together. Avoid treating a missing cache value as proof the original record does not exist; check the authoritative store.",
 takeaway:"Cache the shortcut. Keep a working path to the truth.",diagram:["App checks cache","Miss: database","Store and return"],caption:"On a hit, return immediately. On a miss, fetch the source and populate the cache.",recall:"What are the steps of a cache-aside miss?",
 questions:[q("On a cache-aside miss, what happens next?",["Read the source of truth","Assume the record never existed","Delete the database"],0,["Yes. Fetch the value, populate the cache, and return it.","A cache miss does not prove absence in the database.","The database remains the authoritative source."]),q("A rarely reused query has almost no cache hits. What should you investigate?",["Make every request use more caches","Whether cache overhead outweighs savings","Stop measuring database load"],1,["Additional hops may make the problem worse.","Correct. Caching should save enough repeated work to justify its cost.","Database load helps determine whether the cache actually helps."])]
},
{
 id:"ttl-invalidation",deck:3,title:"When good copies go old",hook:"Even shortcuts need a freshness plan.",
 idea:"A time to live, or TTL, limits how long a cached entry remains usable before expiring. Invalidation removes or marks a copy unusable when its underlying data changes. These mechanisms solve related problems: TTL eventually refreshes copies, while explicit invalidation can react sooner. A TTL alone does not guarantee immediately fresh reads. The actual staleness window also depends on the source read, refresh timing, and any other caching layers.",
 analogy:"A café prints a menu with an expiry date, but crosses out a sold-out item immediately. The date is a safety net. Crossing out the item is a response to new information that should not wait until the menu expires.",
 example:"A product description can tolerate a short period of staleness. A successful edit removes its cached copy so the next read can reload it. Concurrent reads and writes can race: an older database read might repopulate the cache after invalidation. Version checks or carefully designed update flows may be needed.",
 tradeoff:"Short lifetimes improve freshness but increase source traffic. Long lifetimes improve reuse but can serve old information. Decide freshness requirements per feature. Security permissions and inventory reservations need stronger correctness strategies than an arbitrary expiry setting. Test the update path as carefully as the read path.",
 takeaway:"TTL sets an expiry. Invalidation reacts to change.",diagram:["Source changes","Invalidate copy","Next read reloads"],caption:"Expiration is time-based; invalidation responds to an event. Neither removes every race automatically.",recall:"Why does a five-minute TTL not mean an edit is visible immediately?",
 questions:[q("What does TTL primarily specify?",["The owner’s password","A cache entry’s usable lifetime","Unlimited consistency"],1,["TTL is about expiration, not identity.","Correct. It controls when a cached entry expires.","Expiration alone does not provide strong consistency."]),q("A product edit should show up sooner than its TTL. What can help?",["Increase the TTL forever","Ignore the cached copy","Invalidate or refresh it on update"],2,["A longer TTL can extend staleness.","Ignoring the copy leaves readers seeing old data.","Yes. Coordinate invalidation or refresh with updates, and account for concurrent-read races."])]
},
{
 id:"eviction",deck:3,title:"Make room for the useful stuff",hook:"Your cache can’t keep every souvenir.",
 idea:"Eviction removes entries when a cache needs space. It differs from expiration: an entry can be fresh but still be evicted because memory is limited. Least recently used policies favor items accessed recently. Least frequently used policies favor items accessed often. Implementations may approximate these policies to reduce bookkeeping. Some configurations refuse new writes instead of evicting, so check the behavior rather than assuming all caches manage pressure identically.",
 analogy:"A small desk can hold only a few reference books. You might return the book untouched for the longest time or the one you consult least often. Neither choice guarantees that tomorrow’s first question will be easy to answer.",
 example:"A product cache fills during a sale. An eviction policy makes room for new entries, and a later read of an evicted product falls back to the database. Watch hit rate and evictions alongside memory use. A full cache can be healthy, but rapidly churning entries may signal poor sizing or a mismatched workload.",
 tradeoff:"Keeping policy metadata uses resources, and recent activity may not predict future demand. Large one-off scans can displace useful entries. Choose a policy that matches reuse patterns, cap memory deliberately, and ensure eviction never removes the only durable copy of important information.",
 takeaway:"Expiration asks “too old?” Eviction asks “need space?”",diagram:["Memory pressure","Policy chooses","Entry removed"],caption:"An evicted value can still be fresh; the next miss should fall back to the source.",recall:"Can a fresh entry be evicted, and why?",
 questions:[q("Why might a cache evict an unexpired entry?",["To free memory","Because every TTL is zero","To create a durable backup"],0,["Exactly. Space pressure is independent of freshness.","Eviction can happen even with a long remaining TTL.","Eviction removes a copy; it does not make a backup."]),q("A scan pushes useful entries out and hits collapse. What should you examine?",["Only the site’s logo","Reuse patterns, policy, and cache size","Remove the database fallback"],1,["This is a cache workload problem.","Yes. The workload may be causing churn under the current policy and capacity.","Fallback is essential after an eviction or any miss."])]
},
{
 id:"cache-stampedes",deck:3,title:"Don’t all rush the kitchen",hook:"One empty cache. A thousand identical trips.",
 idea:"A cache stampede happens when many requests miss the same popular entry and all try to rebuild it at once. A cache that usually protects the database suddenly sends it a burst of repeated work. Expiration is a common trigger, but cold starts and evictions can cause it too. The important signal is many concurrent computations for the same result, not simply a low hit rate across unrelated keys.",
 analogy:"A café’s display runs out of the most popular sandwich. Every waiter asks the kitchen to make another batch independently. The kitchen becomes overwhelmed even though one coordinated refill could satisfy the waiting customers with far less duplicated effort.",
 example:"A homepage summary expires at noon. Request coalescing lets one in-flight refresh serve multiple waiting requests. Across instances, coordination needs a suitable shared mechanism. Serving a previous value while refreshing can help when stale content is acceptable. Adding jitter to expirations spreads different keys’ refresh times, but does not by itself coordinate a single hot key.",
 tradeoff:"Coordination needs timeouts and failure handling so a crashed refresher does not block everyone forever. Stale-while-revalidate needs an explicit freshness budget. Combine techniques according to the workload, and load-test what happens when the hottest entry disappears rather than testing only a warm cache.",
 takeaway:"Many readers can share one refill.",diagram:["Concurrent misses","One refresh","Shared result"],caption:"Coalesce work for the same key; use bounded waiting and recover if the refresher fails.",recall:"How does request coalescing protect the source during a hot-key miss?",
 questions:[q("What characterizes a cache stampede?",["One ordinary cache hit","Many rebuilds of the same missing result","A larger icon library"],1,["A hit avoids the source work.","Right. Concurrent misses amplify duplicate rebuild work.","This is a concurrency and caching problem."]),q("A popular key expires under heavy traffic. What directly reduces duplicate refreshes?",["Tell every request to retry immediately","Only jitter unrelated keys","Coalesce same-key requests into one refresh"],2,["Immediate retries can increase the overload.","Jitter helps spread different expirations but does not coordinate this hot key.","Exactly. Sharing one bounded refresh avoids repeated source work."])]
},
];
