import type { Lesson, Question } from "./curriculum";
const q = (prompt: string, options: Question["options"], correct: number, explanations: Question["explanations"]): Question => ({prompt,options,correct,explanations});
export const asyncDesign: Lesson[] = [
{
 id:"queues",deck:4,title:"Take a number",hook:"Let work wait without making people wait.",
 idea:"A queue holds work between a producer and a consumer. The producer submits a message, and workers process messages when they have capacity. This separates accepting work from finishing it and can absorb temporary bursts. It does not create unlimited processing capacity: if arrivals keep exceeding completions, the backlog grows. A useful queue dashboard tracks message age as well as count, because a small pile of very old work still matters.",
 analogy:"A bakery takes numbered orders instead of making every customer stand at the oven. Bakers pull orders as they become free. The order slip prevents confusion, but it does not make the ovens bake faster or stop the queue growing forever.",
 example:"After an upload, a service queues a thumbnail job and immediately reports that processing has started. A worker creates the thumbnail and acknowledges the message. If it crashes before acknowledgment, the message may be delivered again. Consumers must handle duplicates, and poison messages need a bounded retry policy and a place for investigation.",
 tradeoff:"Queues add delay and operational complexity. Users need a truthful pending state, not a false claim that work is finished. Ordering and delivery guarantees vary by queue. Set backlog limits, monitor processing age, and make repeated delivery safe before relying on retries for recovery.",
 takeaway:"A queue absorbs bursts; workers still have to do the work.",diagram:["Producer","Work queue","Worker"],caption:"Workers acknowledge completed work; unacknowledged messages may be delivered again.",recall:"Why can a queue smooth a burst but not fix permanent overload?",
 questions:[q("If arrivals permanently exceed processing capacity, what happens?",["The backlog grows","All work finishes instantly","The queue creates extra CPUs"],0,["Yes. Buffering moves waiting; it cannot remove an ongoing capacity shortfall.","Work still needs actual processing time.","Queues need workers with enough resources."]),q("A worker crashes before acknowledgment. What should you expect?",["Guaranteed no redelivery","Possible redelivery, handled safely","Every message disappears forever"],1,["Many queues redeliver unacknowledged work.","Correct. Duplicate-safe consumers make recovery practical.","Durable queues typically retain unacknowledged work under their delivery rules."])]
},
{
 id:"pub-sub",deck:4,title:"One announcement, many ears",hook:"Tell the story once. Let others react.",
 idea:"Publish/subscribe lets a producer publish an event without directly calling every interested consumer. Subscribers receive the event through their subscriptions and react independently. This differs from a competing-consumer work queue, where workers typically share tasks within one consumer group. A system can combine both: each subscription receives an event, then workers within that subscription divide the work. Delivery, retention, and ordering depend on the chosen broker and configuration.",
 analogy:"A school announces a sports day over its bulletin system. Teachers, the kitchen, and the bus team each prepare their part. The announcer does not need to know their internal schedules, but each team must understand what the announcement means.",
 example:"An order-placed event reaches email, analytics, and fulfillment subscribers. A slow analytics subscriber should not delay sending the confirmation. Events need stable identifiers and a clear schema. Consumers should tolerate duplicates and compatible schema additions. An event should describe something that happened, not vaguely demand that unknown recipients do everything.",
 tradeoff:"Loose coupling makes adding reactions easier but obscures the full workflow. Debugging needs correlation IDs, monitoring per subscription, and a plan for failed deliveries. An event reaching the broker does not prove every subscriber finished its work. Track critical business outcomes separately from the act of publication.",
 takeaway:"Publish the fact; subscribers own their reactions.",diagram:["Order event","Topic","Subscriptions"],caption:"Each subscription can receive the event independently; workers within one subscription may share tasks.",recall:"How is an event with several subscriptions different from a shared work queue?",
 questions:[q("What can independent subscriptions do with one event?",["Only one subscription can ever react","Each can perform its own reaction","Automatically share one database transaction"],1,["Fan-out lets multiple subscriptions receive the event.","Exactly. Email and analytics can react independently.","Delivery to subscribers does not create a shared atomic transaction."]),q("The broker accepted an order event. Are all subscriber jobs finished?",["Always","Only if the event is small","No, subscriber outcomes need tracking"],2,["Acceptance and completion are different milestones.","Event size does not prove downstream completion.","Right. Monitor the critical outcomes and each subscription’s progress."])]
},
{
 id:"retries-idempotency",deck:4,title:"Try again. Don’t charge again.",hook:"A timeout is uncertainty, not proof of failure.",
 idea:"A retry repeats an operation after a failure or missing response. The original operation may already have succeeded even if its response was lost. Idempotent behavior means repeating the same intended operation has the same effect as doing it once. For operations such as creating a payment, a client-provided idempotency key can identify one logical attempt. The server must consistently associate that key with the operation and its result.",
 analogy:"You ask a café to prepare order number 42, but cannot hear the reply. Repeating “order 42” should let the café find your original order. Asking for an unnumbered new sandwich each time might create several lunches and several charges.",
 example:"A payment request times out. The client retries with the same key and parameters, and the service returns the recorded outcome instead of charging again. Backoff increases the delay between retries; jitter spreads clients out so they do not all retry simultaneously. Retry only suitable failures, with a bounded budget.",
 tradeoff:"Idempotency needs durable coordination, retention rules, and clear handling of the same key with different parameters. Blind retries can amplify overload, and retrying an invalid request rarely helps. Treat timeouts as unknown outcomes, make effects safe to repeat, and stop retrying when the deadline or budget is exhausted.",
 takeaway:"Repeat the attempt, not the side effect.",diagram:["Same request key","Deduplicate","One logical effect"],caption:"Retry with the same key and intent; bounded backoff with jitter limits extra load.",recall:"Why does a timeout not prove a payment failed?",
 questions:[q("What might a timeout mean?",["The action succeeded but its response was lost","The action definitely never ran","Unlimited retries are safe"],0,["Yes. The outcome is uncertain from the caller’s perspective.","A missing response does not prove missing execution.","Retries need both duplicate safety and a limit."]),q("A payment response was lost. How should a safe retry identify itself?",["Use a new key every time","Reuse the same idempotency key and intent","Change the amount randomly"],1,["A new key can look like a new payment.","Correct. The service can recognize the same logical operation.","Changing intent prevents reliable deduplication of the original operation."])]
},
{
 id:"background-jobs",deck:4,title:"We’ll take it from here",hook:"Long work, honest progress.",
 idea:"A background job performs work outside the user’s immediate request. The application accepts a task, records its identity, and lets a worker finish it separately. A useful lifecycle includes queued, running, succeeded, and failed states. Acceptance does not mean completion. The user needs a way to check status and retrieve a result. Durable state lets that lifecycle survive a browser closing or a worker restarting unexpectedly.",
 analogy:"You leave clothes at a repair shop and receive a ticket. The ticket proves the shop accepted the work, not that the repair is finished. A collection message arrives later, and the shop can explain a delay or a problem.",
 example:"A user requests a large report. The API returns a job ID and a pending status while a worker generates the file. The UI polls a status endpoint at a reasonable interval. Completed reports have authorized download links; failed jobs show a useful explanation and, where appropriate, a safe retry option.",
 tradeoff:"Background processing adds state transitions, cleanup, and recovery logic. A worker can crash halfway through, so partial outputs and repeated execution need careful handling. Bound retries, monitor stuck jobs, and expire old results deliberately. Use a background job when the work warrants it rather than turning every small read into an asynchronous workflow.",
 takeaway:"Accepted is a promise to work, not proof of completion.",diagram:["Submit job","Worker processes","Status and result"],caption:"The client receives a job ID first and checks progress separately from the worker’s execution.",recall:"What should a UI show between job acceptance and completion?",
 questions:[q("What does a job ID returned on submission usually establish?",["The result is definitely finished","The task has been accepted for tracking","The result never needs authorization"],1,["Acceptance happens before completion.","Yes. It identifies a task whose state can be checked.","Outputs can contain private information and still need access control."]),q("Report generation takes three minutes. What is a truthful interface?",["Show success immediately","Keep one spinner forever without status","Show pending status and a completion or failure result"],2,["That promises an outcome that has not happened yet.","Users need bounded, useful status and failure handling.","Exactly. The interface reflects the job’s actual lifecycle."])]
},
{
 id:"consistency",deck:5,title:"Are we seeing the same thing?",hook:"Decide what a read is allowed to know.",
 idea:"Consistency describes the rules for which values reads may observe as data changes. Strong consistency often refers to linearizability: operations behave as if they happened one at a time in an order respecting real-time completion. Eventual consistency allows temporary disagreement, with replicas converging if updates stop and communication succeeds. There are useful guarantees between these extremes, such as read-your-writes, which preserves a user’s view of their own completed updates.",
 analogy:"Friends edit copies of a shared travel plan. Some apps make everyone wait for an agreed update before continuing. Others let copies catch up later. For a packing suggestion, a delay may be fine; for booking the last available seat, it matters much more.",
 example:"A profile page should usually show a user their just-saved name, even if other viewers briefly see the old one. A limited-stock purchase needs a coordinated reservation or transaction that prevents overselling. The right guarantee belongs to the operation, not simply to the entire product’s branding.",
 tradeoff:"Coordination can add latency and make operations unavailable during certain failures. Weaker guarantees simplify some paths but shift complexity into conflict handling and user experience. State the invariant you need, test concurrent operations, and remember that strong reads alone do not make a multi-step read-then-write workflow atomic.",
 takeaway:"Choose what must agree, and when it must agree.",diagram:["Write occurs","Visibility rule","Read observes"],caption:"Consistency defines allowed observations; multi-step invariants may also require transactions or conditional writes.",recall:"Why might profile updates and last-seat reservations need different guarantees?",
 questions:[q("What does read-your-writes provide?",["Visibility of your own completed updates","Zero network latency","Atomicity for every multi-step workflow"],0,["Yes. It prevents your later reads from appearing to forget your own writes.","Visibility guarantees do not remove network time.","That is a stronger and different requirement than seeing your own writes."]),q("Two users attempt to buy the last seat. What protects against overselling?",["A stale cached seat count alone","A coordinated reservation or conditional transaction","A prettier confirmation screen"],1,["A cached number does not safely decide competing reservations.","Correct. Enforce the invariant at the write boundary.","The decision must be correct before the confirmation is displayed."])]
},
{
 id:"cap",deck:5,title:"When the connection breaks",hook:"The real choice behind CAP.",
 idea:"CAP describes a limit for distributed systems during a network partition, when some nodes cannot communicate. In that situation, a system cannot guarantee both linearizable consistency and availability for every request to a non-failing node. In this theorem, availability is a specific formal property, not an uptime percentage. Consistency means a single up-to-date ordering of operations, not merely that records satisfy a schema or business validation rule.",
 analogy:"Two ticket offices lose their shared phone line. Each thinks one seat remains. If both keep selling independently, they may sell the same seat twice. If one refuses to sell until coordination returns, some customers cannot complete a purchase even though that office is running.",
 example:"A partition separates two replicas. A system preserving a single authoritative history may reject or delay operations that cannot reach the required coordination group. Another design might accept operations on both sides and reconcile afterward, giving up the stronger consistency guarantee. Different operations can make different choices.",
 tradeoff:"CAP is not a permanent menu where any two letters solve every design problem. Partitions can happen, and normal operation still involves latency and coordination tradeoffs. Define how each critical operation behaves when communication fails, including recovery and conflict handling, instead of labeling the whole architecture with two letters.",
 takeaway:"During a partition, decide what you refuse to promise.",diagram:["Network split","Choose behavior","Reject or reconcile"],caption:"Under partition, guaranteed linearizability and availability for every request cannot both be retained.",recall:"What does CAP force you to consider specifically during a network partition?",
 questions:[q("When does CAP’s central conflict apply?",["Only when CSS fails","When nodes cannot communicate across a partition","Only when storage is full"],1,["Presentation problems are unrelated to the theorem.","Right. A communication partition creates the consistency-versus-availability conflict.","Disk capacity is a separate failure mode."]),q("Disconnected ticket offices must never oversell one seat. What may be necessary?",["Both sell independently without coordination","Assume partitions never happen","Refuse or delay sales lacking required coordination"],2,["Independent sales can violate the single-seat invariant.","Ignoring a failure mode does not preserve the guarantee.","Yes. Preserving the invariant can require giving up availability for some requests."])]
},
{
 id:"failure-isolation",deck:5,title:"Keep the wobble small",hook:"One broken piece shouldn’t sink the ship.",
 idea:"Failure isolation limits how far one problem can spread. Timeouts bound how long a caller waits. Bulkheads reserve separate resources for different workloads so one cannot consume everything. Circuit breakers temporarily stop calls to a dependency that is failing, allowing limited probes later to see whether it recovered. These mechanisms are related but distinct. A timeout alone may leave underlying work running, so cancellation and resource limits also matter.",
 analogy:"A ship has watertight compartments. A leak in one compartment should not flood the entire hull. Closing a door does not repair the leak, but it protects the rest of the ship while the crew investigates and restores service.",
 example:"A slow recommendation service exhausts the store’s connection pool. Isolate its concurrency budget, use a short bounded deadline, and show a page without recommendations when it fails. Keep checkout resources separate where needed. A circuit breaker can reduce repeated calls during the outage, with cautious probes before normal traffic resumes.",
 tradeoff:"Isolation adds configuration and can leave reserved capacity unused. Aggressive timeouts reject work that might have succeeded, while generous ones can hold resources too long. Choose values from measured behavior and user needs. Test dependency failures deliberately, including slow responses, because partial slowness can be more damaging than a clean crash.",
 takeaway:"Contain the failure before it borrows everyone else’s resources.",diagram:["Slow dependency","Bound and isolate","Core flow survives"],caption:"Separate resource budgets and deadlines protect essential work from optional dependencies.",recall:"How do a timeout, a bulkhead, and a circuit breaker differ?",
 questions:[q("What does a bulkhead primarily separate?",["Resource budgets for different workloads","The spelling of service names","All source code into one file"],0,["Yes. Resource isolation limits how one workload can starve another.","Names alone do not isolate runtime resources.","Source-file layout does not establish runtime capacity boundaries."]),q("Recommendations hang and exhaust connections. What protects checkout?",["Infinite retries through the same pool","Isolated capacity, deadlines, and fallback","Wait without any limit"],1,["That can amplify the outage and exhaust more shared resources.","Correct. Bound optional work and preserve resources for the essential flow.","Unbounded waits let a slow dependency accumulate resource use."])]
},
{
 id:"url-shortener",deck:5,title:"Build something small. Think big.",hook:"Your first system: a URL shortener.",
 idea:"A URL shortener maps a short code to a longer destination. Start with two operations: create a mapping and resolve a code. Clarify requirements before adding machinery: should links expire, can destinations change, and how many reads and writes are expected? A basic design uses an application and a durable store with a unique constraint on the code. Reads look up the mapping and return an HTTP redirect to the destination.",
 analogy:"A coat-check ticket is a compact reference to a larger item. The ticket number needs to identify the right coat reliably. Giving two people the same active ticket number creates a problem no amount of faster retrieval can fix.",
 example:"Generate a random code, attempt an insert protected by a uniqueness constraint, and retry if it collides. Randomness reduces collisions but does not prove uniqueness. Cache frequently resolved mappings when read load justifies it. Handle unknown and expired codes explicitly, validate allowed URL schemes, and plan abuse controls before exposing public creation.",
 tradeoff:"Caching improves popular redirects but complicates destination edits and expiry. Analytics can be queued so they do not block redirects. Avoid sharding or microservices until measured requirements need them. Explain the create and resolve paths, identify failure cases, then add only the components that solve a demonstrated problem.",
 takeaway:"Start with the contract. Add boxes only when they earn their place.",diagram:["Short code","Mapping lookup","HTTP redirect"],caption:"Creation stores a unique code-to-URL mapping; resolution finds it and redirects the caller.",recall:"What are the two main operations, and how would you prevent code collisions?",
 questions:[q("What guarantees that an inserted short code is unique?",["Random generation alone","A uniqueness constraint with collision handling","A short filename"],1,["Random codes can still collide.","Exactly. The store enforces uniqueness while the application handles conflicts.","Filenames do not guarantee mapping uniqueness."]),q("Redirects are fast, but analytics writes are slow. What is a reasonable next step?",["Shard every table immediately","Wait for analytics before every redirect","Queue analytics separately from the redirect path"],2,["That adds complexity without targeting this bottleneck.","Nonessential analytics would slow the core user action.","Yes. Decoupling analytics protects redirect latency while retaining the work."])]
},
];
